class Server():
    name = None
    verbose_name = None
    _verbose_name = None
    primary_key = False
    max_length = 255
    _unique = False
    blank = False
    null = False
    remote_field = None
    is_relation = False
    default = <class 'django.db.models.fields.NOT_PROVIDED'>
    editable = True
    serialize = True
    unique_for_date = None
    unique_for_month = None
    unique_for_year = None
    choices = None
    help_text = 
    db_index = False
    db_column = None
    db_comment = None
    _db_tablespace = None
    auto_created = False
    creation_counter = 117
    _validators = []
    _error_messages = None
    db_collation = None
    validators = [<django.core.validators.MaxLengthValidator object at 0x000001AB559FBBF0>]

class Date():
    name = None
    verbose_name = None
    _verbose_name = None
    primary_key = False
    max_length = 255
    _unique = False
    blank = False
    null = False
    remote_field = None
    is_relation = False
    default = <class 'django.db.models.fields.NOT_PROVIDED'>
    editable = True
    serialize = True
    unique_for_date = None
    unique_for_month = None
    unique_for_year = None
    choices = None
    help_text = 
    db_index = False
    db_column = None
    db_comment = None
    _db_tablespace = None
    auto_created = False
    creation_counter = 118
    _validators = []
    _error_messages = None
    db_collation = None
    validators = [<django.core.validators.MaxLengthValidator object at 0x000001AB55D39EE0>]

class Content-Type():
    name = None
    verbose_name = None
    _verbose_name = None
    primary_key = False
    max_length = 255
    _unique = False
    blank = False
    null = False
    remote_field = None
    is_relation = False
    default = <class 'django.db.models.fields.NOT_PROVIDED'>
    editable = True
    serialize = True
    unique_for_date = None
    unique_for_month = None
    unique_for_year = None
    choices = None
    help_text = 
    db_index = False
    db_column = None
    db_comment = None
    _db_tablespace = None
    auto_created = False
    creation_counter = 119
    _validators = []
    _error_messages = None
    db_collation = None
    validators = [<django.core.validators.MaxLengthValidator object at 0x000001AB55D3A540>]

class Content-Length():
    name = None
    verbose_name = None
    _verbose_name = None
    primary_key = False
    max_length = 255
    _unique = False
    blank = False
    null = False
    remote_field = None
    is_relation = False
    default = <class 'django.db.models.fields.NOT_PROVIDED'>
    editable = True
    serialize = True
    unique_for_date = None
    unique_for_month = None
    unique_for_year = None
    choices = None
    help_text = 
    db_index = False
    db_column = None
    db_comment = None
    _db_tablespace = None
    auto_created = False
    creation_counter = 120
    _validators = []
    _error_messages = None
    db_collation = None
    validators = [<django.core.validators.MaxLengthValidator object at 0x000001AB55D397F0>]

class Connection():
    name = None
    verbose_name = None
    _verbose_name = None
    primary_key = False
    max_length = 255
    _unique = False
    blank = False
    null = False
    remote_field = None
    is_relation = False
    default = <class 'django.db.models.fields.NOT_PROVIDED'>
    editable = True
    serialize = True
    unique_for_date = None
    unique_for_month = None
    unique_for_year = None
    choices = None
    help_text = 
    db_index = False
    db_column = None
    db_comment = None
    _db_tablespace = None
    auto_created = False
    creation_counter = 121
    _validators = []
    _error_messages = None
    db_collation = None
    validators = [<django.core.validators.MaxLengthValidator object at 0x000001AB55D3A960>]

class Content-Encoding():
    name = None
    verbose_name = None
    _verbose_name = None
    primary_key = False
    max_length = 255
    _unique = False
    blank = False
    null = False
    remote_field = None
    is_relation = False
    default = <class 'django.db.models.fields.NOT_PROVIDED'>
    editable = True
    serialize = True
    unique_for_date = None
    unique_for_month = None
    unique_for_year = None
    choices = None
    help_text = 
    db_index = False
    db_column = None
    db_comment = None
    _db_tablespace = None
    auto_created = False
    creation_counter = 122
    _validators = []
    _error_messages = None
    db_collation = None
    validators = [<django.core.validators.MaxLengthValidator object at 0x000001AB55D3BF50>]

class X-Cs-Region():
    name = None
    verbose_name = None
    _verbose_name = None
    primary_key = False
    max_length = 255
    _unique = False
    blank = False
    null = False
    remote_field = None
    is_relation = False
    default = <class 'django.db.models.fields.NOT_PROVIDED'>
    editable = True
    serialize = True
    unique_for_date = None
    unique_for_month = None
    unique_for_year = None
    choices = None
    help_text = 
    db_index = False
    db_column = None
    db_comment = None
    _db_tablespace = None
    auto_created = False
    creation_counter = 123
    _validators = []
    _error_messages = None
    db_collation = None
    validators = [<django.core.validators.MaxLengthValidator object at 0x000001AB55D39D60>]

class X-Cs-Traceid():
    name = None
    verbose_name = None
    _verbose_name = None
    primary_key = False
    max_length = 255
    _unique = False
    blank = False
    null = False
    remote_field = None
    is_relation = False
    default = <class 'django.db.models.fields.NOT_PROVIDED'>
    editable = True
    serialize = True
    unique_for_date = None
    unique_for_month = None
    unique_for_year = None
    choices = None
    help_text = 
    db_index = False
    db_column = None
    db_comment = None
    _db_tablespace = None
    auto_created = False
    creation_counter = 124
    _validators = []
    _error_messages = None
    db_collation = None
    validators = [<django.core.validators.MaxLengthValidator object at 0x000001AB55D3A390>]

class X-Ratelimit-Limit():
    name = None
    verbose_name = None
    _verbose_name = None
    primary_key = False
    max_length = 255
    _unique = False
    blank = False
    null = False
    remote_field = None
    is_relation = False
    default = <class 'django.db.models.fields.NOT_PROVIDED'>
    editable = True
    serialize = True
    unique_for_date = None
    unique_for_month = None
    unique_for_year = None
    choices = None
    help_text = 
    db_index = False
    db_column = None
    db_comment = None
    _db_tablespace = None
    auto_created = False
    creation_counter = 125
    _validators = []
    _error_messages = None
    db_collation = None
    validators = [<django.core.validators.MaxLengthValidator object at 0x000001AB55D3A5A0>]

class X-Ratelimit-Remaining():
    name = None
    verbose_name = None
    _verbose_name = None
    primary_key = False
    max_length = 255
    _unique = False
    blank = False
    null = False
    remote_field = None
    is_relation = False
    default = <class 'django.db.models.fields.NOT_PROVIDED'>
    editable = True
    serialize = True
    unique_for_date = None
    unique_for_month = None
    unique_for_year = None
    choices = None
    help_text = 
    db_index = False
    db_column = None
    db_comment = None
    _db_tablespace = None
    auto_created = False
    creation_counter = 126
    _validators = []
    _error_messages = None
    db_collation = None
    validators = [<django.core.validators.MaxLengthValidator object at 0x000001AB55D3A150>]

class Strict-Transport-Security():
    name = None
    verbose_name = None
    _verbose_name = None
    primary_key = False
    max_length = 255
    _unique = False
    blank = False
    null = False
    remote_field = None
    is_relation = False
    default = <class 'django.db.models.fields.NOT_PROVIDED'>
    editable = True
    serialize = True
    unique_for_date = None
    unique_for_month = None
    unique_for_year = None
    choices = None
    help_text = 
    db_index = False
    db_column = None
    db_comment = None
    _db_tablespace = None
    auto_created = False
    creation_counter = 127
    _validators = []
    _error_messages = None
    db_collation = None
    validators = [<django.core.validators.MaxLengthValidator object at 0x000001AB55D3A570>]

class __module__():

