import django.db.models as models
class Server():
    name = None
    verbose_name = None
    _verbose_name = None
    primary_key = False
    max_length = 255
    _unique = False
    blank = False
    null = False
    remote_field = None
    is_relation = False
    default = <class 'django.db.models.fields.NOT_PROVIDED'>
    editable = True
    serialize = True
    unique_for_date = None
    unique_for_month = None
    unique_for_year = None
    choices = None
    help_text = 
    db_index = False
    db_column = None
    db_comment = None
    _db_tablespace = None
    auto_created = False
    creation_counter = 104
    _error_messages = None
    db_collation = None
    validators0 = ['__call__', '__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_constructor_args', 'clean', 'code', 'compare', 'deconstruct', 'limit_value', 'message']

class Date():
    name = None
    verbose_name = None
    _verbose_name = None
    primary_key = False
    max_length = 255
    _unique = False
    blank = False
    null = False
    remote_field = None
    is_relation = False
    default = <class 'django.db.models.fields.NOT_PROVIDED'>
    editable = True
    serialize = True
    unique_for_date = None
    unique_for_month = None
    unique_for_year = None
    choices = None
    help_text = 
    db_index = False
    db_column = None
    db_comment = None
    _db_tablespace = None
    auto_created = False
    creation_counter = 105
    _error_messages = None
    db_collation = None
    validators0 = ['__call__', '__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_constructor_args', 'clean', 'code', 'compare', 'deconstruct', 'limit_value', 'message']

class Content_Type():
    name = None
    verbose_name = None
    _verbose_name = None
    primary_key = False
    max_length = 255
    _unique = False
    blank = False
    null = False
    remote_field = None
    is_relation = False
    default = <class 'django.db.models.fields.NOT_PROVIDED'>
    editable = True
    serialize = True
    unique_for_date = None
    unique_for_month = None
    unique_for_year = None
    choices = None
    help_text = 
    db_index = False
    db_column = None
    db_comment = None
    _db_tablespace = None
    auto_created = False
    creation_counter = 106
    _error_messages = None
    db_collation = None
    validators0 = ['__call__', '__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_constructor_args', 'clean', 'code', 'compare', 'deconstruct', 'limit_value', 'message']

class Content_Length():
    name = None
    verbose_name = None
    _verbose_name = None
    primary_key = False
    max_length = 255
    _unique = False
    blank = False
    null = False
    remote_field = None
    is_relation = False
    default = <class 'django.db.models.fields.NOT_PROVIDED'>
    editable = True
    serialize = True
    unique_for_date = None
    unique_for_month = None
    unique_for_year = None
    choices = None
    help_text = 
    db_index = False
    db_column = None
    db_comment = None
    _db_tablespace = None
    auto_created = False
    creation_counter = 107
    _error_messages = None
    db_collation = None
    validators0 = ['__call__', '__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_constructor_args', 'clean', 'code', 'compare', 'deconstruct', 'limit_value', 'message']

class Connection():
    name = None
    verbose_name = None
    _verbose_name = None
    primary_key = False
    max_length = 255
    _unique = False
    blank = False
    null = False
    remote_field = None
    is_relation = False
    default = <class 'django.db.models.fields.NOT_PROVIDED'>
    editable = True
    serialize = True
    unique_for_date = None
    unique_for_month = None
    unique_for_year = None
    choices = None
    help_text = 
    db_index = False
    db_column = None
    db_comment = None
    _db_tablespace = None
    auto_created = False
    creation_counter = 108
    _error_messages = None
    db_collation = None
    validators0 = ['__call__', '__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_constructor_args', 'clean', 'code', 'compare', 'deconstruct', 'limit_value', 'message']

class Content_Encoding():
    name = None
    verbose_name = None
    _verbose_name = None
    primary_key = False
    max_length = 255
    _unique = False
    blank = False
    null = False
    remote_field = None
    is_relation = False
    default = <class 'django.db.models.fields.NOT_PROVIDED'>
    editable = True
    serialize = True
    unique_for_date = None
    unique_for_month = None
    unique_for_year = None
    choices = None
    help_text = 
    db_index = False
    db_column = None
    db_comment = None
    _db_tablespace = None
    auto_created = False
    creation_counter = 109
    _error_messages = None
    db_collation = None
    validators0 = ['__call__', '__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_constructor_args', 'clean', 'code', 'compare', 'deconstruct', 'limit_value', 'message']

class X_Cs_Region():
    name = None
    verbose_name = None
    _verbose_name = None
    primary_key = False
    max_length = 255
    _unique = False
    blank = False
    null = False
    remote_field = None
    is_relation = False
    default = <class 'django.db.models.fields.NOT_PROVIDED'>
    editable = True
    serialize = True
    unique_for_date = None
    unique_for_month = None
    unique_for_year = None
    choices = None
    help_text = 
    db_index = False
    db_column = None
    db_comment = None
    _db_tablespace = None
    auto_created = False
    creation_counter = 110
    _error_messages = None
    db_collation = None
    validators0 = ['__call__', '__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_constructor_args', 'clean', 'code', 'compare', 'deconstruct', 'limit_value', 'message']

class X_Cs_Traceid():
    name = None
    verbose_name = None
    _verbose_name = None
    primary_key = False
    max_length = 255
    _unique = False
    blank = False
    null = False
    remote_field = None
    is_relation = False
    default = <class 'django.db.models.fields.NOT_PROVIDED'>
    editable = True
    serialize = True
    unique_for_date = None
    unique_for_month = None
    unique_for_year = None
    choices = None
    help_text = 
    db_index = False
    db_column = None
    db_comment = None
    _db_tablespace = None
    auto_created = False
    creation_counter = 111
    _error_messages = None
    db_collation = None
    validators0 = ['__call__', '__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_constructor_args', 'clean', 'code', 'compare', 'deconstruct', 'limit_value', 'message']

class X_Ratelimit_Limit():
    name = None
    verbose_name = None
    _verbose_name = None
    primary_key = False
    max_length = 255
    _unique = False
    blank = False
    null = False
    remote_field = None
    is_relation = False
    default = <class 'django.db.models.fields.NOT_PROVIDED'>
    editable = True
    serialize = True
    unique_for_date = None
    unique_for_month = None
    unique_for_year = None
    choices = None
    help_text = 
    db_index = False
    db_column = None
    db_comment = None
    _db_tablespace = None
    auto_created = False
    creation_counter = 112
    _error_messages = None
    db_collation = None
    validators0 = ['__call__', '__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_constructor_args', 'clean', 'code', 'compare', 'deconstruct', 'limit_value', 'message']

class X_Ratelimit_Remaining():
    name = None
    verbose_name = None
    _verbose_name = None
    primary_key = False
    max_length = 255
    _unique = False
    blank = False
    null = False
    remote_field = None
    is_relation = False
    default = <class 'django.db.models.fields.NOT_PROVIDED'>
    editable = True
    serialize = True
    unique_for_date = None
    unique_for_month = None
    unique_for_year = None
    choices = None
    help_text = 
    db_index = False
    db_column = None
    db_comment = None
    _db_tablespace = None
    auto_created = False
    creation_counter = 113
    _error_messages = None
    db_collation = None
    validators0 = ['__call__', '__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_constructor_args', 'clean', 'code', 'compare', 'deconstruct', 'limit_value', 'message']

class Strict_Transport_Security():
    name = None
    verbose_name = None
    _verbose_name = None
    primary_key = False
    max_length = 255
    _unique = False
    blank = False
    null = False
    remote_field = None
    is_relation = False
    default = <class 'django.db.models.fields.NOT_PROVIDED'>
    editable = True
    serialize = True
    unique_for_date = None
    unique_for_month = None
    unique_for_year = None
    choices = None
    help_text = 
    db_index = False
    db_column = None
    db_comment = None
    _db_tablespace = None
    auto_created = False
    creation_counter = 114
    _error_messages = None
    db_collation = None
    validators0 = ['__call__', '__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_constructor_args', 'clean', 'code', 'compare', 'deconstruct', 'limit_value', 'message']

class __module__():

